---
env: stage

# Can be one of: [ aws, azure, gcp ]
cloud_provider: "aws"

# Should match the name of the cluster in the selected Cloud Provider
cluster_name: "gbh-stage"

deployment:
  # Can be one of: [ ansible, werf ]
  provider: werf

container_registry:
  # Can be one of: [ acr, ecr, gcr ]
  type: ecr
  url: 091791791455.dkr.ecr.us-east-1.amazonaws.com/production/internal-jobs

# Only used if deployment.provider is werf
werf:
  # Applications/services managed by Werf (must match werf.yaml images)
  services: ["api", "web"]
  # Additional files to be added to Werf commands with `--values`
  # and `--secret-values` independently of the environment (applies to all templates).
  values_files: [".helm/custom-env-vars.yaml"]
  secrets_files: [".helm/custom-secret-vars.yaml"]
  # Additional paths where files will be added to Werf commands with `--values`
  # and `--secret-values` independently of the environment (applies to all templates).
  values: [".helm/values", ".helm/extra-values"]
  secrets: [".helm/secrets"]

git:
  default_branch: main
