---
env: stage

cloud_provider: "aws"

cluster_name: "gbh-stage"

deployment:
  # Can be one of: [ ansible, werf ]
  provider: werf

container_registry:
  # Can be one of: [ acr, ecr, gcr ]
  type: ecr
  url: there
