name: 🛠️ Build

on:
  pull_request:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout current code ref
        uses: actions/checkout@v6

      - name: 🔵 Set up Go on runner
        uses: actions/setup-go@v6
        with:
            go-version-file: go.mod
            cache-dependency-path: go.sum

      - name: 🛠️ Run build
        run: go build
