name: 🚀 Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TERM: xterm-256color

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: 💻 Checkout current project revision
        uses: actions/checkout@v6
        with:
          token: '${{ secrets.DEVOPS_USER_TOKEN }}'

      - name: 🟢 Configure Node.js on runner
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: 💼 Configure Git user
        run: |
          git config user.name "gbh-devops-bot"
          git config user.email "devops@gbh.tech"

      - name: Bump versions & create changelogs
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: '${{ secrets.DEVOPS_USER_TOKEN }}'
          HUSKY: 0
        with:
          publish: npx @changesets/cli publish && git push --follow-tags
          version: npx @changesets/cli version
          setupGitUser: false
          createGithubReleases: true
          title: 'chore: version packages'
          commit: 'chore: version packages'
